### PR TITLE
Merge in upstream master

### PR DESCRIPTION
**Pull request by stevevls**
This brings us up to v1.2.2 plus a few additional commits on master.

### CODE REVIEW

**Comment by stevevls** [comment]
Failing check is from circleci.com, but we don't use that anymore.

**Review by Pryz — APPROVED** [review]

**Comment by stevevls** [comment]
Oops...thought I closed this.  I stopped using our fork in https://github.com/segmentio/treb-apps/pull/59

**Comment by Pryz** [comment]
We may want to add something to the readme to mark it as deprecated then :)

**Comment by stevevls** [comment]
What do you think about boneyarding it?

**Pull request closed without merging**
